### ISSUE TITLE
Make `frontend` unprivileged

### ISSUE THREAD

**Issue by mathieu-benoit** [mathieu-benoit/deploy-backstage-with-score#80]
In `Dockerfile.frontend`:
```yaml
...
FROM nginxinc/nginx-unprivileged:alpine-slim
USER root
RUN apk update && apk add jq && rm -rf /var/lib/apk/lists/*
COPY --from=build /app/packages/app/dist /usr/share/nginx/html
COPY container-config/default.conf.template /etc/nginx/templates/default.conf.template
COPY container-config/inject-config.sh /docker-entrypoint.d/40-inject-config.sh
USER $UID
ENV PORT=8080
```

In `score-frontend.yaml`:
```yaml
apiVersion: score.dev/v1b1
metadata:
  name: frontend
containers:
  frontend:
    image: .
    ...
    volumes:
      /tmp:
        source: ${resources.tmp}
        readOnly: false
      /etc/nginx/conf.d:
        source: ${resources.confd}
        readOnly: false
      /usr/share/nginx/html/static:
        source: ${resources.static}
        readOnly: false
...
resources:
  tmp:
    type: volume
  confd:
    type: volume
  static:
    type: volume
```

But still getting this error at runtime:
```none
sed: can't create temp file '/usr/share/nginx/html/static/module-backstage.8b957130.jsXXXXXX': Permission denied
```

Need to still investigate... maybe we can have the `inject-config.sh` and `default.conf.template` mounted as `files` in Score file in order to get the placeholders replacements made at deployment time?

And then add back the `--patch-templates https://raw.githubusercontent.com/score-spec/community-patchers/refs/heads/main/score-compose/unprivileged.tpl \` in `Makefile`.

References:
- https://github.com/nginx/docker-nginx-unprivileged/issues/88
- https://gist.github.com/monosoul/e462b03cba5542bfc52f135417a8209d
